### ISSUE TITLE
Add Umbraco to the 2019 Hacktoberfest Swag List

### ISSUE THREAD

**Issue by mohatagarvit** [crweiner/hacktoberfest-swag-list#156]
Find the relevant details for umbraco from this DEV [post](https://dev.to/m1guelpf/hacktoberfest-2019-swag-list-3ajg).

Rest of the organizations I believe are already added.

**Comment by crweiner** [comment]
Sooooooo, here's the deal. Umbraco apparently doesn't like this little project. See [the past post here that includes some tweets from their devs](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-535131859). There's more tweets in that thread...

I don't understand their position at all. It makes literally no sense. "We want to promote Hacktoberfest and have our own swag! Oh, but don't tell anyone because we'll get a few bad apples."  Also, they don't want people to get their swag by submitting low-quality PRs but have nothing in place to screen PRs as other companies are doing.

They don't seem to understand that their swag is a tool for **marketing and promotion** not a payment for completing a job.

As I tried to explain to them, I'll never be an Umbraco dev, but I wore their shirt to a tech conference and had 3 people ask me about it. Because I earned their swag, I knew about the company and was able to talk about it with 3 different people who have never heard about it before. Because again, swag = marketing, swag ≠ payment.

I said that I'd keep them off the list and will do so unless hear differently by those Umbraco devs who asked to be excluded. I also personally don't wish to promote a company that only wants to focus on the few negatives and negates the spirit of Hacktoberfest (which is open and honest collaboration).

Reach out to them on Twitter, GitHub, or wherever to ask their opinion. 

I try to be a man of my word, so they don't want to be on this list and I'll be honoring that for at least 2019. We'll see what their stance is in the future.

**Comment by lex111** [comment]
@crweiner you are absolutely right, I will even stop helping this project, I wanted to him... but now I won’t!

**Comment by crweiner** [comment]
> @crweiner you are absolutely right, I will even stop helping this project, I wanted to him... but now I won’t!

Hay @lex111 that's totally up to you. They certainly need good people to contribute to their code and their swag is up for grabs for meaningful PRs. They just don't want to use this project/site/repo to promote Umbraco and I'll be honoring that for 2019 with a goal of reaching out again in 2020.

**Comment by lex111** [comment]
Well.. I created several PR's with considerable corrections in their docs, and I wanted to continue working, because this is an interesting project, but I did not know their position regarding HF event. It was unpleasant for me to find out, because I’m helping **not** for the sake of swag, it’s offensive to some extent!

**Comment by nul800sebastiaan** [comment]
Hi again @crweiner - I have of course heard your arguments on Twitter, which is not a place for constructive discussions. 
Of course there will still be bad apples, that's not the point, we just have rules for them this year and we only send swag for awesome contributions like the ones @lex111 has been sending (thank you Alexy! 🙏).

As for promotion/marketing opportunities: thanks for wearing the t-shirt, that's great! We need to be conscious about how we spend our marketing budget wisely and don't feel like hacktoberfest swag fits in our marketing strategy right now. For us this is not a marketing opportunity, it is a month to celebrate collaborating closely with our community.

Our stance is merely that, this month, we're reaching out to our existing community, the people already using Umbraco who have a direct interest in sending us improvements. Our experience last year was unfortunately that quite a few contributors told us they heard about us specifically from this list. While we appreciate all the help we can get, these people also never returned until this year to do another contribution. 

We believe that we have all the tools already to reach our community and help them engage more in our project. We find it unlikely that this list will reach existing Umbraco users. In the end, the contributions any project really needs are the ones from people using the product who can use their existing (or new-found!) knowledge to make improvements.

That said, of course we wholeheartedly welcome people who want to help a project that they have no personal connection to (thanks again @lex111!) and welcome their contributions with open arms. 

I hope this explains our position a bit better than I could ever do on Twitter. Thanks again for your interest and I hope you have great success with the Hacktoberfest Swag List project!

**Comment by crweiner** [comment]
Hay there @nul800sebastiaan! :smile: 

>I have of course heard your arguments on Twitter, which is not a place for constructive discussions.

Yes, that does tend to turn into a shouting match and I am guilty of that... 

> we just have rules for them this year and we only send swag for awesome contributions

Exactly! I don't think that is being effectively communicated, however. More on that later.

>For us this is not a marketing opportunity, it is a month to celebrate collaborating closely with our community. Our stance is merely that, this month, we're reaching out to our existing community, the people already using Umbraco who have a direct interest in sending us improvements.

That is totally fine. It's your own giveaway after all. Even though I see swag as merely a marketing opportunity (as it is for any conference you may attend), you can certainly see it as a reward for improvements (even if I don't personally agree with that).

To that end, I'd suggest only offering swag then to people who are members of [Our](https://our.umbraco.com/) before Hacktoberfest starts. Or only offer swag for people who fix specifically-tagged "Hacktoberfest" Issues that you create instead of any merged PR. Or perhaps only offer swag for fixing bugs or adding new features? That way, you know that they are both contributing based on their past status as a member of the Umbraco community as well as fixing the needs you need taken care of the most.

Set the bar high and communicate that upfront! Having essentially 1 merged PR as a requirement as you do now is going to lead to lots of drive-by PRs regardless.

>Our experience last year was unfortunately that quite a few contributors told us they heard about us specifically from this list.

Awww, shucks. :blush: Thank you! I'm glad that I can point people towards cool open-source projects! :+1:  That's my goal!

>While we appreciate all the help we can get, these people also never returned until this year to do another contribution.
>We find it unlikely that this list will reach existing Umbraco users.

You're probably 100% correct. It isn't likely to reach existing Umbraco users at all. That's what Our is for, your mailing lists, people who have purchased support packages, etc. Believe me, I completely get that this isn't targeting your regular users. 

Even though you've gotten a rush of PRs during Hacktoberfest from only people who contribute during Hacktoberfest, have they been meaningful? As in, have the repeat people who only contribute during Hacktoberfest done so with the goal of actually contributing meaningful changes or just submitting junk? 

I think that you can certainly have people who only contribute during Hacktoberfest because of the publicity surrounding the holiday and [your own blog post telling them that everyone can contribute](https://umbraco.com/blog/hacktoberfest-2019/). If you get a wave of people who come to fix your docs each year, then cool! At least every October you know that you're going to get everything fixed up by the same people who contributed last year because they know of Umbraco and recognize how they can play their part once a year to help.

Maybe people like @lex111 are an exception to the rule? Perhaps you are getting more negative PRs than helpful ones from repeat Hacktoberfest-only contributors? You'd certainly have better data regarding that than I.

If you want to only reach existing Umbraco users then you have many ways to do that instead of announcing free swag to the world via your public blog for several years and then getting annoyed when you get junk in response.

If your position is to stick to only existing Umbraco community members this year, then I'd only ask that you treat this project just like all of the others. You should ask that Umbraco be taken off of [here](https://devswag.io/) (which gets much, much, more traffic than this repo), [here](https://benbarth.github.io/hacktoberfest-swag/), [here](https://dev.to/m1guelpf/hacktoberfest-2019-swag-list-3ajg), etc. These other lists are also shouting out Umbraco's participation in Hacktoberfest to a much larger audience than my project.

> In the end, the contributions any project really needs are the ones from people using the product who can use their existing (or new-found!) knowledge to make improvements.

Absolutely, I agree that the most meaningful contributions are those that fix a true need. See all I've said above on how you can do that for next year by setting the bar high and communicating the requirements clearer.

>That said, of course we wholeheartedly welcome people who want to help a project that they have no personal connection to ... and welcome their contributions with open arms.

That's the opposite of what you've been saying. You want for people to have a personal connection with Umbraco because your goal is to "reach out to our existing community". Which, again, you are certainly in your own right to do as it's your swag. But you're giving mixed signals here. 

If you actually want outside help from people with no prior connection to Umbraco, you've got to get the word out regarding Umbraco. How else do they find you? That's exactly what I'm trying to do here; connect people to cool projects they haven't seen before. I found Umbraco last year and wanted to share your project with the world. :heart: 

If you want for it to only be your existing community members, then post something privately in Our that only logged-in members can see. That'll cut down on the number of non-regulars contributing to you for Hacktoberfest. 

You've got to pick a side and stick with it.

>Thanks again for your interest and I hope you have great success with the Hacktoberfest Swag List project!

I appreciate it! Believe me, I'd love to see Umbraco grow as well! That's the spirit of open-source and Hacktoberfest; everyone helping each other out and smacking down the opportunists that come our way just for free stuff. :wink: 

---

As I said, I'll stick to my word and keep Umbraco off of the list and reconnect with you in 2020. If you're willing to share it with me, I'd love to get a sense of your contributor data for this year and see if keeping you off of this list has improved the quality of PRs you received (outside of your hosted hackathons, which should obviously produce high-quality PRs). 

My thought is that the cat's out of the bag for this year anyway and you're going to get lots of drive-by swag-seeking PRs regardless, but who knows? :man_shrugging: 

Thank you again for your time, Sebastiaan. Be well!

**Comment by lex111** [comment]
@nul800sebastiaan thank you for clarifying your position, it seems to me that this is quite fair, but the first time you did not explain it well enough, so this caused outrage..

From my own experience I will say that I heard about Umbarco from this awwwesome list, and I am very grateful to @crweiner for that! :muscle: 

I don’t see anything bad that some people (including me) learn about the open-source projects they want to help during the HF event.
But here you need to understand that this is unlikely to be your target audience, it will also be short-term help, and PRs will not be of such high quality. But someone among these participants will become an active contributor, or something else..

However I still want to believe that this is really useful,  although a little help to the OS project. In the end, you can mark PR as 'invalid' if it is not of significant value.

That’s what I like about Hacktoberfest, because in October for the third time I will learn about cool and interesting open-source projects and I can take part in them. This is a very amazing feeling, you know. Swag in this case, it is just a pleasant (but not essential) some sort of reward or gift. 

I am glad that we got things sorted out and therefore this issue can be closed. :heart:

**Comment by sahil-9** [comment]
@crweiner So I feel you should marked this issue as closed?
