### ISSUE TITLE
I want to add a tic tac toe project based on c++ and minimax algorithm

### ISSUE THREAD

**Issue by Amulya77** [crweiner/hacktoberfest-swag-list#399]
This is my first ever open source contribution and I want to add a tic tac toe project based on c++ and minimax algorithm

**Comment by PurviBhoyar21** [comment]
Hello @crweiner 
I am a contributor participating in hacktoberfest 2021
I would love to do this project of c++.
Please assign me this issue
so that I can start working on it as soon as possible.
Thank you

**Comment by crweiner** [comment]
Hey @PurviBhoyar21 and @Amulya77, thanks for checking out the Hacktoberfest Swag List!

PRs and contributions such as this are not necessary and cause frustration in repo maintainers like myself. Copying and pasting a wall of code from some other site isn't helpful and isn't in the spirit of Hacktoberfest.

I'd also like to remind you that view the [Hacktoberfest Quality Standards](https://hacktoberfest.digitalocean.com/resources) and take some time reading over the Quality Standards and Participation sections. 

Another thing to keep in mind...all of your PRs to **public** repos are also _**public**_...so anyone can just click on your name, see the other spammy PRs and/or walls of copy-and-pasted text you've submitted to other repos, and then [report those repos to the Hacktoberfest team](https://hacktoberfest.digitalocean.com/report) if the repos are not following the Hacktoberfest Guidelines.

If you wish to make meaningful contributions to this project, then please follow [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md). Otherwise, look for repos tagged ```Hacktoberfest``` and provide real, meaningful help.

Hope that helps to point you in the right direction. Have a great Hacktoberfest. 👍
