### ISSUE TITLE
Overlaping github info with footer. 

### ISSUE THREAD

**Issue by AlexInes** [crweiner/hacktoberfest-swag-list#442]
Hey, 
I am using Firefox 92.0.1 (64-bit) on macOS Big Sur v. 11.6 13 inch macbook. 
At the very end of you page footer info overlap with github badges. Just moving footer text might solve it. 

<img width="1275" alt="Screenshot 2021-10-05 at 09 49 01" src="https://user-images.githubusercontent.com/9095124/135983048-96b4a48e-0138-4105-acd8-6b78b24b514e.png">

**Comment by crweiner** [comment]
Hey @AlexInes! Thank you for pointing this out! I've also got a 13" MacBook Pro and noticed that issue. It's just an odd screen size, I guess. 🤷

Believe it or not, this was even worse, as brought up in Issue #93 and fixed in PR #122.

If you want to submit a PR to try and fix this, please go ahead! Otherwise, I can tackle it in a bit. 👍

Hope you're having a good Hacktoberfest! 😎😎

**Comment by AlexInes** [comment]
I would love too!
