### ISSUE TITLE
add circleCI to participating companies

### ISSUE THREAD

**Issue by ksmorano** [crweiner/hacktoberfest-swag-list#45]
just saw on twitter :)
https://circleci-public.github.io/hacktoberfest/#/

**Comment by crweiner** [comment]
Yes indeed! It's great to see a new company on the list!! And the shirt looks really cool!!

![Woot Woot!](https://media.giphy.com/media/xTkcELYYToYreWwe8U/giphy.gif)

Thanks for the heads up and keep them coming! Let's have a wonderful swag-filled Hacktoberfest. :-)

**Comment by ksmorano** [comment]
can I PR those I know of?

**Comment by KyleTryon** [comment]
Yall are so fast! I just submitted a PR: https://github.com/crweiner/hacktoberfest-swag-list/pulls

**Comment by crweiner** [comment]
I had first wanted to hold off on adding things to the list until Hacktoberfest began to give as many people as possible the chance to earn 4 PRs and the official swag. However, I also clearly see the merit of hitting the ground running with a full swag list instead of starting to build it on Oct 1st. 

I'll leave it up to you and amend my wording in #44. If you think that you will be able to easily complete your 4 PRs during Hacktoberfest, then you can go ahead and add companies offering swag now. If you'd like for your PRs to count towards the official Hacktoberfest swag, then wait until you officially sign up on Oct 1 and submit your PRs then.

Does that sound fair to all?

**Comment by crweiner** [comment]
@ksmorano Long story short I changed my mind. Yes you can PR those you know of now as long as you know that it won't count yet towards the official swag.

I merged the CircleCI PR submitted by @KyleTryon and I would love to see what others you can submit or if you'd like to [appease the markdown lint bot](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/46) :robot:

**Comment by crweiner** [comment]
Because CircleCI has been added, I'll close this Issue. Feel free to open up a new issue and submit your PRs! I just don't want to get people confused and try to add CircleCI twice. :smile:
