### ISSUE TITLE
Add dyrectorio to the  Hacktoberfest Swag List

### ISSUE THREAD

**Issue by vimode** [crweiner/hacktoberfest-swag-list#631]
[dyrector.io ](https://docs.dyrector.io/) giving a dyrectorio swag cap for writing unit tests with 10% coverage in the golang side of the repository

More details available [here](https://github.com/dyrector-io/dyrectorio/issues/241)

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting before submitting a PR. 

@crweiner This looks more like a one time bounty than the hacktoberfest event. What do you think?

**Comment by AbhishekTiwari23** [comment]
I completed this task. Please accept m previous pr so that I can make a fresh pr for this one also

**Comment by crweiner** [comment]
> I completed this task. Please accept m previous pr so that I can make a fresh pr for this one also

@AbhishekTiwari23: You don't have to add things one at a time, feel free to group several companies together into one PR. You don't want to artificially inflate your PR count for Hacktoberfest...right?🤨 Plus, it makes my job easier to review. 👍 

Your PR #630 is pulling from your `master` branch, so anything else you add there will be included in the same PR automatically.  Just update the title of that PR to reflect all of the companies you wish to add at once, please.

BTW, [this isn't necessary for the small change you had](https://github.com/AbhishekTiwari23/hacktoberfest-swag-list/pull/1). If this happened to be an attempt to +1 your own PR count, that's against the spirit of Hacktoberfest and won't work anyway. I see this a lot...I get tagged in the PR of someone's fork because they don't realize it notifies me. 🔔 

If you're pulling together several branches, with each branch having it's own new organization to add, and _then_ purposely submitting one PR that has everyone in it, then sure that's one way to do it. 😀 

If it's a mistake and that meant to be a PR against that repo here, then honest mistake! Happens all the time! 😄 This repo draws lots of first-timers and I've seen that mistake plenty of times before.

**Comment by AbhishekTiwari23** [comment]
> > I completed this task. Please accept m previous pr so that I can make a fresh pr for this one also
> 
> @AbhishekTiwari23: You don't have to add things one at a time, feel free to group several companies together into one PR. You don't want to artificially inflate your PR count for Hacktoberfest...right?🤨 Plus, it makes my job easier to review. 👍
> 
> Your PR #630 is pulling from your `master` branch, so anything else you add there will be included in the same PR automatically. Just update the title of that PR to reflect all of the companies you wish to add at once, please.
> 
> BTW, [this isn't necessary for the small change you had](https://github.com/AbhishekTiwari23/hacktoberfest-swag-list/pull/1). If this happened to be an attempt to +1 your own PR count, that's against the spirit of Hacktoberfest and won't work anyway. I see this a lot...I get tagged in the PR of someone's fork because they don't realize it notifies me. 🔔
> 
> If you're pulling together several branches, with each branch having it's own new organization to add, and _then_ purposely submitting one PR that has everyone in it, then sure that's one way to do it. 😀
> 
> If it's a mistake and that meant to be a PR against that repo here, then honest mistake! Happens all the time! 😄 This repo draws lots of first-timers and I've seen that mistake plenty of times before.

Ok, I will take care of it. Thanks

**Comment by vimode** [comment]
You're welcome @crweiner  And thank you for your intention with this repo. 

With some goodies, they naturally surface on twitter, reddit etc 
And just some age old keyword specific search alerts 🤖  but that is slowly becoming less useful to find such issues as people are flooding their profiles with `hacktoberfest` and `hacktoberfest2022` titled repos, to game the system with dummy repos that are filled with silly submissions. 😩 
On the bright side, I think this time around so far the organizers have it under control. I also am seeing some of these repos being updated with the note that it got excluded from `hacktoberfest`. And they add a link to the new dummy one 🙃

**Comment by crweiner** [comment]
Be sure to report any spam repos you see [via this form](https://hacktoberfest.com/report/) so the Hacktoberfest team can take care of it. That's also how this project got flagged initially, and I can totally see how someone can make that assumption by a casual glance. 😅

**Comment by vimode** [comment]
Awesome.  Thank you for the link. Will be reporting them from now on. 

Sidenote, its a bit unfortunate that Gitlab's repo search is auth walled which is probably by barely anything get indexed as such, discovery for those projects will be fairly low. 

If I am not mistaken, this is the first them Gitlab repos too are part of hacktoberfest, isn't it? The reception might not be as huge as it is over Github. 😞

**Comment by crweiner** [comment]
> If I am not mistaken, this is the first them Gitlab repos too are part of hacktoberfest, isn't it? The reception might not be as huge as it is over Github. 😞

[This is their second year](https://about.gitlab.com/blog/2021/10/01/join-us-for-hacktoberfest-2021/) and last year they offered their own swag too, I believe. GitLab has often been for more corporate / business-y folks compared to the free-for-all that GitHub is. 😆 They had a free set of integrated CI/CD before GitHub launched Actions, so I used them for a bit, but GitHub pulled me back because of allllllll the integrations they have and the bigger community. ❤️

**Comment by vimode** [comment]
Interesting. No wonder their CI/CD service was much easier to work with a yml file than Github Actions. 
I also keep reading that Github is not even on parity with the features Gitlab provides! 
Yes, the bigger community and the openness definitely is a great driver of Github's popularity.
