### ISSUE TITLE
Add techstacks in descriptions 

### ISSUE THREAD

**Issue by Ruchika30** [crweiner/hacktoberfest-swag-list#666]
I think adding techstack along with the other details by an organization would be a helpful addition. As of now we got to their respective repos and check the techstacks if relevant to a certain developer for him./her to checkout the issues in them

**Comment by kev-odin** [comment]
Can you provide an example of what you mean?

What problem are you trying to solve?

**Comment by vimode** [comment]
Its a really neat suggestion but most of the projects in this list are from companies which have multiple repos with a big list of languages use for various purposes.  That could make each item very crowded very quickly. 

I personally do not like the idea of this being a curated list, could develop a selection bias like behavior from the source(here), by limiting what a contributor can provide based on what they already know. It feels like a very limiting approach and doesn't leave any room for the contributor to explorer on their own. 

Many a times you would not know anything about the project but find it really interesting once you visit them and wish to contribute. I think this also ties in well with the spirit of hacktoberfest to learn new things.

**Comment by crweiner** [comment]
I appreciate the suggestion, @Ruchika30, but at this point adding a tech stack / coding language field isn't something I wish to implement at this time. 

New for 2022, [no-code and low-code contributions are very much encoraged](https://hacktoberfest.com/about/#low-or-non-code), and I don't want to _discourage_ someone from contributing to a repo/project they find interesting simply because they do not know the main programming language of that repo. Companies on this list actively want to draw attention to their repos, and I'd like to send as many good people their way as possible. 

Additionally, part of the success of the Hacktoberfest Swag List is its' simplicity. It's a list. For Hacktoberfest. That's it. 🤓 There's very few pictures, lots of links, and it's designed to be searchable and get you _off the List_ to go and start helping. I wish to reduce the complexity as much as possible for people contributing to this project and using it to find great organizations to help.

Again, thank you for your suggestion and I hope you understand my position and goals for this project. Have a wonderful Hacktoberfest!! ❤️

**Comment by Ruchika30** [comment]
> language

I understand . Thank you
