### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by benbarth** [crweiner/hacktoberfest-swag-list#8]
This project appears to be a duplicate of https://github.com/benbarth/hacktoberfest-swag

**Comment by crweiner** [comment]
Hay @benbarth! Thanks for pointing me in the direction of your swag list too. Yours looks much better than mine. :smiley: 

I was looking across GitHub for something like this and couldn't find it before. I'm not sure how I missed your list, but somehow I guess I did. So, I set out to put up a list mainly so I can make sure that I know of all of the swag opportunities for this Hacktoberfest (see my attempt at a checklist [here](https://github.com/crweiner/hacktoberfest-swag-list/blob/personal-checklist/Checklist.md))

I know that this is the age of the internet, and it's your word against mine, but if I had seen your list before then I wouldn't have gone through the trouble of trying to make my own list. Any duplication from your list is completely unintentional because this is the first I've even seen it.

Is there anything in particular you're looking for? I think we can help each other out, like you can add source{d} to your list and I can add Typeform to mine. :+1:  Let me know your thoughts!

**Comment by benbarth** [comment]
No worries! I hadn't seen a Hacktoberfest swag list before https://benbarth.github.io/hacktoberfest-swag/ but it's probably not the first. I'm working on a general swag list as well. *Coming soon*
I'm still working on a good format to display items.
Team work sounds great. Can't have too much swag. ;)

**Comment by crweiner** [comment]
I was totally going to work on a general dev swag list site too a few months ago, then I came across this one: https://github.com/swapagarwal/swag-for-dev
It doesn't seem to be complete, even though the repo is active. That should be a good jumping off point to help your dev swag list. I'll keep an eye on your repo and see what other cool stuff you can find!

**Comment by crweiner** [comment]
Operation Code's participation in Hacktoberfest 2018 isn't very well documented, but it's on their banner here: https://github.com/OperationCode/START_HERE
It was just added in a PR by one of the people behind the project, see PR #6

**Comment by crweiner** [comment]
Closing in order to begin to set things up for Hacktoberfest 2019. If you wish to collaborate between all of us and [Swag For Dev](https://github.com/swapagarwal/swag-for-dev) then we can do so by following his [JSON](https://github.com/swapagarwal/swag-for-dev/blob/master/data.json) format. Also, see Issue #26.

Let's make this next Hacktoberfest a great one! :-)
